// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpsahmaxljekrpmpbejt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwc2FobWF4bGpla3JwbXBiZWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTQ4MTksImV4cCI6MjA1ODczMDgxOX0.ReJ0Fj3aIBxaoIETuu5rtPVvu7023zcs4oTj1jR1Dk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);